### PR TITLE
Update imgpkg port settings

### PR DESCRIPTION
**Pull request by shashwathi**
### What this PR does / why we need it

Update CI local registry port settings.

### CODE REVIEW

**Review by rashedkvm — APPROVED** [review]
lgtm - I believe the original intent using two different ports may have been to validate the image relocation.

**Comment by scothis** [comment]
> I believe the original intent using two different ports may have been to validate the image relocation.

It was purely cosmetic. The registry the bundle is created against shows up inside the bundle if you crack it open. I was trying to avoid the port number showing up there.

**Comment by rashedkvm** [comment]
> > I believe the original intent using two different ports may have been to validate the image relocation.
> 
> It was purely cosmetic. The registry the bundle is created against shows up inside the bundle if you crack it open. I was trying to avoid the port number showing up there.

Now I know. Hey there @scothis! Good to hear from you.

**Comment by rashedkvm** [comment]
@scothis I came up with this proposed change in CI.yaml. The same issue was found in a few other repos. What I don't understand, how did this passed before?  The new variant is the new version of `imgpkg` v0.23.0. It is still a puzzle, perhaps for a later time. I have built a mock of the CI scripts and will investigate them in the next open cycle.

**Pull request merged**
