### PR TITLE
updated Carvel package name

### PR DESCRIPTION
**Pull request by rashedkvm**
Signed-off-by: Rashed Kamal <krashed@vmware.com>

### CODE REVIEW

**Comment by scothis** [comment]
Why? This is a vmware-labs project

**Comment by rashedkvm** [comment]
> Why? This is a vmware-labs project

This was a suggestion from TAP packaging team - similar to the naming convention used here https://gitlab.eng.vmware.com/tap/tap-packages/-/merge_requests/29. Consistency in naming is the motivation here.

**Comment by rashedkvm** [comment]
> Why? This is a vmware-labs project

Consistent naming with TAP packaging

**Comment by rashedkvm** [comment]
Closing PR - update path in TAP packaging

**Pull request closed without merging**
